/**
 * @openapi
 * components:
 *   schemas:
 *     ErrorCode:
 *       type: string
 *       enum:
 *         - DISABLED_ACCOUNT
 *         - EXPIRED_TOKEN
 *         - FILE_NOT_FOUND
 *         - FILE_TOO_LARGE
 *         - INCORRECT_PASSWORD
 *         - INTERNAL_SERVER_ERROR
 *         - INVALID_FILE_FORMAT
 *         - INVALID_INPUT
 *         - INVALID_TOKEN
 *         - MISSING_JWT_VALIDATION
 *         - PERMISSION_DENIED
 *         - UNACTIVATED_ACCOUNT
 *         - USER_NOT_FOUND
 */
export enum ErrorCode {
  DISABLED_ACCOUNT = 'DISABLED_ACCOUNT',
  EXPIRED_TOKEN = 'EXPIRED_TOKEN',
  FILE_NOT_FOUND = 'FILE_NOT_FOUND',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
  INCORRECT_PASSWORD = 'INCORRECT_PASSWORD',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  INVALID_FILE_FORMAT = 'INVALID_FILE_FORMAT',
  INVALID_INPUT = 'INVALID_INPUT',
  INVALID_TOKEN = 'INVALID_TOKEN',
  MISSING_JWT_VALIDATION = 'MISSING_JWT_VALIDATION',
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  UNACTIVATED_ACCOUNT = 'UNACTIVATED_ACCOUNT',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
}
